######################################
# Update and upgrade
######################################
- name: update and upgrade apt
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

######################################
# Generic tools
######################################
- name: Install usefull system tools
  apt: name={{ item }} state=present
  with_items:
    - vim
    - htop
    - git
    - openssl
    - tmux
    - curl
    - tar
    - nano
    - rsync

######################################
# Time management
######################################
- name: Set local timezone
  ansible.builtin.timezone:
    name: Asia/Ho_Chi_Minh

######################################
# Copy system files
######################################
- name: add profile common
  copy:
    src: common.sh
    dest: /etc/profile.d/common.sh
    owner: "root"
    group: "root"
    mode: 0755
