# Deploy this file as a Splunk application, for example:
# %SPLUNK_HOME%\etc\apps\goad_sysmon\local\inputs.conf

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
disabled = 0
renderXml = true
current_only = 0
checkpointInterval = 5
sourcetype = XmlWinEventLog:Microsoft-Windows-Sysmon/Operational
